### ISSUE TITLE
Is the input_x in line150 and line136 same?

### ISSUE THREAD

**Issue by feynman233** [taki0112/ResNeXt-Tensorflow#1]
Hi, I have found that in the function residual_layer(), the loop {for i in range(res_block):}  has the same input_x in its each iteration.
I'm not sure if it's right，can you explain it？
Thanks！

**Comment by taki0112** [comment]
I am sorry to see this issue late.
I've fixed the issue you mentioned.
Thank you for telling me.

```python
x = Relu(x + pad_input_x) -> input_x = Relu(x + pad_input_x)
```
