### ISSUE TITLE
 do you have the pretrain model about ResNeXt by tensorflow

### ISSUE THREAD

**Issue by zmyu** [taki0112/ResNeXt-Tensorflow#3]
hi taki0112
im looking for a pre-train model about resnext by tensorflow , can u offer a link about your pretrain model to fine-turn? thanks

**Comment by taki0112** [comment]
The pre train model is stored on the previous company server, so I can not do it.

As soon as I receive the gpu in current company(naver), I will train again to raise the pre-train.

**Comment by insikk** [comment]
@taki0112 Have you finished training this model? I would be really nice to share pretrained model of this implementation.
