### ISSUE TITLE
residual_layer should return input_x

### ISSUE THREAD

**Issue by aayux** [taki0112/ResNeXt-Tensorflow#4]
In Line [#161](https://github.com/taki0112/ResNeXt-Tensorflow/blob/e2f4c763f086270a27dd873f5957dc7e9f9cf2d0/ResNeXt.py#L161) of `ResNeXt.py`, shouldn't `residual_layer` return `input_x`?

This discrepancy may have come up because of #1. Can you please confirm?

**Comment by taki0112** [comment]
oh.. Very Thank you.. ! 
that's right ! 
I modified
