### ISSUE TITLE
Where is the Residual?

### ISSUE THREAD

**Issue by machuck** [taki0112/ResNeXt-Tensorflow#5]
Shouldn't the conv2d function be something like below? 

```
def Conv2d(...):
   weights=tf.Variable(...)
   biases=tf.Variable(...)
   network=tf.layers.conv2d(input_x, ....)
   network = network + biases
   network = network + input_x
   return network
```

I don't see the residual network in your code, please advise. Thanks!

**Comment by taki0112** [comment]
In [residual_layer](https://github.com/taki0112/ResNeXt-Tensorflow/blob/master/ResNeXt.py#L136)
you cas see `input_x = Relu(x + pad_input_x)`
